const preGeneratedPrompts = [
  'Une forêt dense et sombre avec des arbres couverts de neige',
  'Un château médiéval sur une colline verdoyante',
  'Un paysage urbain futuriste avec des gratte-ciels lumineux',
  'Un océan agité avec des vagues énormes et des nuages orageux',
  'Une ville en ruine avec des bâtiments en feu',
  'Un jardin japonais traditionnel avec des ponts en bois et des carpes koï',
  "Une vue panoramique d'une plage tropicale avec des palmiers et des cocotiers",
  'Un désert aride avec des dunes de sable et un coucher de soleil rougeoyant',
  'Une ville enneigée avec des rues illuminées et des vitrines de magasins',
  'Un lac paisible avec des bateaux à voile et des oiseaux migrateurs',
  'Une grotte mystérieuse avec des stalactites et des stalagmites',
  'Un champ de fleurs sauvages avec des papillons et des libellules',
  "Un parc d'attractions avec des montagnes russes et des manèges colorés",
  'Un temple ancien avec des statues de dieux et des fresques',
  'Une forêt de bambous avec des singes et des oiseaux exotiques',
  'Une ville enneigée avec des rues illuminées et des vitrines de magasins',
  'Un parc national avec des animaux sauvages et des montagnes enneigées',
  'Une ville futuriste avec des véhicules volants et des immeubles à énergie solaire',
  'Une île tropicale avec des plages de sable blanc et des palmiers',
  'Un château hanté avec des fenêtres brisées et des portes grinçantes',
  'Un jardin botanique avec des plantes rares et des fleurs exotiques',
  'Une ville portuaire avec des bateaux et des grues',
  "Un parc d'attractions avec des montagnes russes et des manèges colorés",
  'Un lac paisible avec des bateaux à voile et des oiseaux migrateurs',
  'Une ville moderne avec des gratte-ciels et des immeubles en verre',
  'Un désert aride avec des dunes de sable et un coucher de soleil rougeoyant',
  'Une ville en ruine avec des bâtiments en feu',
  'Un temple ancien avec des statues de dieux et des fresques',
  'Un jardin japonais traditionnel avec des ponts en bois et des carpes koï',
  'Une grotte sous-marine avec des coraux et des poissons colorés',
  'Un parcours de golf avec des collines verdoyantes et des étangs',
  'Une ferme avec des vaches et des champs de blé',
  'Une ville historique avec des bâtiments en pierre et des rues pavées',
  "Un parc d'attractions avec des montagnes russes et des manèges colorés",
  'Une plage avec des parasols et des transats',
  'Une ville enneigée avec des rues illuminées et des vitrines de magasins',
  'Un paysage de montagne avec des sommets enneigés et des lacs de montagne',
  'Une forêt luxuriante avec des cascades et des ruisseaux',
  'Une ville moderne avec des gratte-ciels et des immeubles en verre',
  'Une ville futuriste avec des véhicules volants et des immeubles à énergie solaire',
  'Un château hanté avec des fenêtres brisées et des portes grinçantes',
  'Un parc national avec des animaux sauvages et des montagnes enneigées',
  'Un lac paisible avec des bateaux à voile et des oiseaux migrateurs',
  'Un jardin botanique avec des plantes rares et des fleurs exotiques',
  'Une ville portuaire avec des bateaux et des grues',
  "Un parc d'attractions avec des montagnes russes et des manèges colorés",
  'Une île tropicale avec des plages de sable blanc et des palmiers',
  'Une ville en ruine avec des bâtiments en feu',
  'Un temple ancien avec des statues de dieux et des fresques',
  'Une grotte sous-marine avec des coraux et des poissons colorés',
  'Une ville futuriste avec des immeubles connectés et des voitures autonomes',
  'Une usine désaffectée avec des machines rouillées et des graffiti',
  'Un parcours de golf avec des collines verdoyantes et des étangs',
  'Une ferme avec des vaches et des champs de blé',
  'Une ville historique avec des bâtiments en pierre et des rues pavées',
  "Un parc d'attractions avec des montagnes russes et des manèges colorés",
  'Une plage avec des parasols et des transats',
  'Une ville enneigée avec des rues illuminées et des vitrines de magasins',
  'Un paysage de montagne avec des sommets enneigés et des lacs de montagne',
  'Une forêt luxuriante avec des cascades et des ruisseaux',
  'Une ville moderne avec des gratte-ciels et des immeubles en verre',
  'Une ville futuriste avec des véhicules volants et des immeubles à énergie solaire',
  'Un château hanté avec des fenêtres brisées et des portes grinçantes',
  'Un parc national avec des animaux sauvages et des montagnes enneigées',
  'Un lac paisible avec des bateaux à voile et des oiseaux migrateurs',
  'Un jardin botanique avec des plantes rares et des fleurs exotiques',
  'Une ville portuaire avec des bateaux et des grues',
  "Un parc d'attractions avec des montagnes russes et des manèges colorés",
  'Une île tropicale avec des plages de sable blanc et des palmiers',
  'Une ville en ruine avec des bâtiments en feu',
  'Un temple ancien avec des statues de dieux et des fresques',
];

export default preGeneratedPrompts;
